
cc = cc or {}

-- TMX
cc.TMX_ORIENTATION_ORTHO     = 0x0
cc.TMX_ORIENTATION_HEX       = 0x1
cc.TMX_ORIENTATION_ISO       = 0x2
cc.TMX_ORIENTATION_STAGGERED = 0x3
cc.TMX_STAGGER_AXIS_X = 0x0
cc.TMX_STAGGER_AXIS_Y = 0x1
cc.TMX_STAGGER_INDEX_ODD = 0x0
cc.TMX_STAGGER_INDEX_EVEN = 0x1
cc.TMX_TILE_HORIZONTAL_FLAG = 0x80000000
cc.TMX_TILE_VERTICAL_FLAG   = 0x40000000
cc.TMX_TILE_DIAGONAL_FLAG   = 0x20000000
cc.TMX_TILE_FLIPED_ALL      = 0xE0000000
cc.TMX_TILE_FLIPPEDMASK     = 0x1FFFFFFF
-- cc ZipUtils
cc.Z_COMPRESSION_ZLIB   = 0x0
cc.Z_COMPRESSION_BZIP2  = 0x1
cc.Z_COMPRESSION_GZIP   = 0x2
cc.Z_COMPRESSION_NONE   = 0x3
-- tag
cc.ACTION_TAG_INVALID   = -1
cc.NODE_TAG_INVALID = -1
-- director
cc.DIRECTOR_PROJECTION_2D   = 0x0
cc.DIRECTOR_PROJECTION_3D   = 0x1
cc.DIRECTOR_PROJECTION_CUSTOM   = 0x2
cc.DIRECTOR_PROJECTION_DEFAULT  = 0x1
cc.ResolutionPolicy =
{
    EXACT_FIT = 0,
    NO_BORDER = 1,
    SHOW_ALL  = 2,
    FIXED_HEIGHT  = 3,
    FIXED_WIDTH  = 4,
    UNKNOWN  = 5,
}
cc.MATRIX_STACK_TYPE =
{
    MODELVIEW = 0,
    PROJECTION = 1,
    TEXTURE = 2,
}
-- particle
cc.PARTICLE_DURATION_INFINITY   = -1
cc.PARTICLE_START_SIZE_EQUAL_TO_END_SIZE    = -1
cc.PARTICLE_START_RADIUS_EQUAL_TO_END_RADIUS    = -1
cc.PARTICLE_MODE_GRAVITY = 0x0
cc.PARTICLE_MODE_RADIUS  = 0x1
cc.POSITION_TYPE_FREE   = 0x0
cc.POSITION_TYPE_RELATIVE   = 0x1
cc.POSITION_TYPE_GROUPED    = 0x2
-- ProgressTimer
cc.PROGRESS_TIMER_TYPE_RADIAL = 0x0
cc.PROGRESS_TIMER_TYPE_BAR    = 0x1
-- Text
cc.TEXT_ALIGNMENT_LEFT   = 0x0
cc.TEXT_ALIGNMENT_CENTER = 0x1
cc.TEXT_ALIGNMENT_RIGHT  = 0x2
cc.VERTICAL_TEXT_ALIGNMENT_TOP    = 0x0
cc.VERTICAL_TEXT_ALIGNMENT_CENTER = 0x1
cc.VERTICAL_TEXT_ALIGNMENT_BOTTOM = 0x2
-- Touch
cc.TOUCHES_ALL_AT_ONCE  = 0x0
cc.TOUCHES_ONE_BY_ONE   = 0x1
cc.EventCode =
{
    BEGAN = 0,
    MOVED = 1,
    ENDED = 2,
    CANCELLED = 3,
}
-- TransitionScene
cc.TRANSITION_ORIENTATION_LEFT_OVER  = 0x0
cc.TRANSITION_ORIENTATION_RIGHT_OVER = 0x1
cc.TRANSITION_ORIENTATION_UP_OVER    = 0x0
cc.TRANSITION_ORIENTATION_DOWN_OVER  = 0x1
-- Application
cc.PLATFORM_OS_WINDOWS = 0
cc.PLATFORM_OS_LINUX   = 1
cc.PLATFORM_OS_MAC     = 2
cc.PLATFORM_OS_ANDROID = 3
cc.PLATFORM_OS_IPHONE  = 4
cc.PLATFORM_OS_IPAD    = 5
-- Language Type
cc.LANGUAGE_ENGLISH    = 0
cc.LANGUAGE_CHINESE    = 1
cc.LANGUAGE_FRENCH     = 2
cc.LANGUAGE_ITALIAN    = 3
cc.LANGUAGE_GERMAN     = 4
cc.LANGUAGE_SPANISH    = 5
cc.LANGUAGE_DUTCH      = 6
cc.LANGUAGE_RUSSIAN    = 7
cc.LANGUAGE_KOREAN     = 8
cc.LANGUAGE_JAPANESE   = 9
cc.LANGUAGE_HUNGARIAN  = 10
cc.LANGUAGE_PORTUGUESE = 11
cc.LANGUAGE_ARABIC     = 12
cc.LANGUAGE_NORWEGIAN  = 13
cc.LANGUAGE_POLISH     = 14
cc.LANGUAGE_TURKISH    = 15
cc.LANGUAGE_UKRAINIAN  = 16
cc.LANGUAGE_ROMANIAN   = 17
cc.LANGUAGE_BULGARIAN  = 18
cc.LANGUAGE_BELARUSIAN = 19
-- Editbox
cc.KEYBOARD_RETURNTYPE_DEFAULT = 0
cc.KEYBOARD_RETURNTYPE_DONE = 1
cc.KEYBOARD_RETURNTYPE_SEND = 2
cc.KEYBOARD_RETURNTYPE_SEARCH = 3
cc.KEYBOARD_RETURNTYPE_GO = 4
cc.KEYBOARD_RETURNTYPE_NEXT = 5

cc.EDITBOX_INPUT_MODE_ANY = 0
cc.EDITBOX_INPUT_MODE_EMAILADDR = 1
cc.EDITBOX_INPUT_MODE_NUMERIC = 2
cc.EDITBOX_INPUT_MODE_PHONENUMBER = 3
cc.EDITBOX_INPUT_MODE_URL = 4
cc.EDITBOX_INPUT_MODE_DECIMAL = 5
cc.EDITBOX_INPUT_MODE_SINGLELINE = 6

cc.EDITBOX_INPUT_FLAG_PASSWORD = 0
cc.EDITBOX_INPUT_FLAG_SENSITIVE = 1
cc.EDITBOX_INPUT_FLAG_INITIAL_CAPS_WORD = 2
cc.EDITBOX_INPUT_FLAG_INITIAL_CAPS_SENTENCE = 3
cc.EDITBOX_INPUT_FLAG_INITIAL_CAPS_ALL_CHARACTERS = 4
cc.EDITBOX_INPUT_FLAG_LOWERCASE_ALL_CHARACTERS = 5
-- Handler Type
cc.Handler = cc.Handler or {}
cc.Handler.NODE = 0
cc.Handler.CALLFUNC = 1
cc.Handler.WEBSOCKET_OPEN = 2
cc.Handler.WEBSOCKET_MESSAGE = 3
cc.Handler.WEBSOCKET_CLOSE = 4
cc.Handler.WEBSOCKET_ERROR = 5
cc.Handler.LUANODE_DRAW = 6
cc.Handler.EVENT_ACC = 7
cc.Handler.EVENT_CUSTIOM = 8
cc.Handler.EVENT_KEYBOARD_PRESSED = 9
cc.Handler.EVENT_KEYBOARD_RELEASED = 10
cc.Handler.EVENT_TOUCH_BEGAN = 11
cc.Handler.EVENT_TOUCH_MOVED = 12
cc.Handler.EVENT_TOUCH_ENDED = 13
cc.Handler.EVENT_TOUCH_CANCELLED = 14
cc.Handler.EVENT_TOUCHES_BEGAN = 15
cc.Handler.EVENT_TOUCHES_MOVED = 16
cc.Handler.EVENT_TOUCHES_ENDED = 17
cc.Handler.EVENT_TOUCHES_CANCELLED = 18
cc.Handler.EVENT_MOUSE_DOWN = 19
cc.Handler.EVENT_MOUSE_UP = 20
cc.Handler.EVENT_MOUSE_MOVE = 21
cc.Handler.EVENT_MOUSE_SCROLL = 22
cc.Handler.EVENT_PHYSICS_CONTACT_BEGIN = 23
cc.Handler.EVENT_PHYSICS_CONTACT_PRESOLVE = 24
cc.Handler.EVENT_PHYSICS_CONTACT_POSTSOLVE = 25
cc.Handler.EVENT_PHYSICS_CONTACT_SEPARATE = 26
cc.Handler.EVENT_FOCUS = 27
cc.Handler.EVENT_CONTROLLER_CONNECTED = 28
cc.Handler.EVENT_CONTROLLER_DISCONNECTED = 29
cc.Handler.EVENT_CONTROLLER_KEYDOWN = 30
cc.Handler.EVENT_CONTROLLER_KEYUP = 31
cc.Handler.EVENT_CONTROLLER_KEYREPEAT = 32
cc.Handler.EVENT_CONTROLLER_AXIS = 33
cc.Handler.EVENT_SPINE_ANIMATION_START = 34
cc.Handler.EVENT_SPINE_ANIMATION_INTERRUPT = 35
cc.Handler.EVENT_SPINE_ANIMATION_END = 36
cc.Handler.EVENT_SPINE_ANIMATION_DISPOSE = 37
cc.Handler.EVENT_SPINE_ANIMATION_COMPLETE = 38
cc.Handler.EVENT_SPINE_ANIMATION_EVENT = 39
cc.Handler.EVENT_SPINE_ANIMATION_PREUPDATE = 40
cc.Handler.EVENT_SPINE_ANIMATION_POSTUPDATE = 41
-- EventListener Type
cc.EVENT_UNKNOWN               = 0
cc.EVENT_TOUCH_ONE_BY_ONE      = 1
cc.EVENT_TOUCH_ALL_AT_ONCE     = 2
cc.EVENT_KEYBOARD              = 3
cc.EVENT_MOUSE                 = 4
cc.EVENT_ACCELERATION          = 5
cc.EVENT_FOCUS                 = 6
cc.EVENT_GAME_CONTROLLER       = 7
cc.EVENT_CUSTOM                = 8
-- physics
cc.PHYSICSSHAPE_MATERIAL_DEFAULT = {density = 0.0, restitution = 0.0, friction = 0.0}
cc.PHYSICSBODY_MATERIAL_DEFAULT = {density = 0.1, restitution = 0.5, friction = 0.5}
-- Label
cc.GLYPHCOLLECTION_DYNAMIC = 0
cc.GLYPHCOLLECTION_NEHE    = 1
cc.GLYPHCOLLECTION_ASCII   = 2
cc.GLYPHCOLLECTION_CUSTOM  = 3
cc.LabelEffect =
{
    NORMAL = 0,
    OUTLINE = 1,
    SHADOW = 2,
    GLOW = 3,
    ITALICS = 4,
    BOLD = 5,
    UNDERLINE = 6,
    STRIKETHROUGH = 7,
    ALL = 8
}
cc.LabelOverflow =
{
    NONE = 0,
    CLAMP = 1,
    SHRINK = 2,
    RESIZE_HEIGHT = 3
}
-- Mouse
cc.MouseButton = {
	BUTTON_UNSET = -1,
	BUTTON_LEFT = 0,
	BUTTON_RIGHT = 1,
	BUTTON_MIDDLE = 2,
	BUTTON_4 = 3,
	BUTTON_5 = 4,
	BUTTON_6 = 5,
	BUTTON_7 = 6,
	BUTTON_8 = 7
}
-- keyboard
cc.KeyCode =
{
	KEY_NONE = 0,
	KEY_PAUSE = 1,
	KEY_SCROLL_LOCK = 2,
	KEY_PRINT = 3,
	KEY_SYSREQ = 4,
	KEY_BREAK = 5,
	KEY_ESCAPE = 6,
	KEY_BACKSPACE = 7,
	KEY_TAB = 8,
	KEY_BACK_TAB = 9,
	KEY_RETURN = 10,
	KEY_CAPS_LOCK = 11,
	KEY_LEFT_SHIFT = 12,
	KEY_RIGHT_SHIFT = 13,
	KEY_LEFT_CTRL = 14,
	KEY_RIGHT_CTRL = 15,
	KEY_LEFT_ALT = 16,
	KEY_RIGHT_ALT = 17,
	KEY_MENU = 18,
	KEY_HYPER = 19,
	KEY_INSERT = 20,
	KEY_HOME = 21,
	KEY_PG_UP = 22,
	KEY_DELETE = 23,
	KEY_END = 24,
	KEY_PG_DOWN = 25,
	KEY_LEFT_ARROW = 26,
	KEY_RIGHT_ARROW = 27,
	KEY_UP_ARROW = 28,
	KEY_DOWN_ARROW = 29,
	KEY_NUM_LOCK = 30,
	KEY_KP_PLUS = 31,
	KEY_KP_MINUS = 32,
	KEY_KP_MULTIPLY = 33,
	KEY_KP_DIVIDE = 34,
	KEY_KP_ENTER = 35,
	KEY_KP_HOME = 36,
	KEY_KP_UP = 37,
	KEY_KP_PG_UP = 38,
	KEY_KP_LEFT = 39,
	KEY_KP_FIVE = 40,
	KEY_KP_RIGHT = 41,
	KEY_KP_END = 42,
	KEY_KP_DOWN = 43,
	KEY_KP_PG_DOWN = 44,
	KEY_KP_INSERT = 45,
	KEY_KP_DELETE = 46,
	KEY_F1 = 47,
	KEY_F2 = 48,
	KEY_F3 = 49,
	KEY_F4 = 50,
	KEY_F5 = 51,
	KEY_F6 = 52,
	KEY_F7 = 53,
	KEY_F8 = 54,
	KEY_F9 = 55,
	KEY_F10 = 56,
	KEY_F11 = 57,
	KEY_F12 = 58,
	KEY_SPACE = 59,
	KEY_EXCLAM = 60,
	KEY_QUOTE = 61,
	KEY_NUMBER = 62,
	KEY_DOLLAR = 63,
	KEY_PERCENT = 64,
	KEY_CIRCUMFLEX = 65,
	KEY_AMPERSAND = 66,
	KEY_APOSTROPHE = 67,
	KEY_LEFT_PARENTHESIS = 68,
	KEY_RIGHT_PARENTHESIS = 69,
	KEY_ASTERISK = 70,
	KEY_PLUS = 71,
	KEY_COMMA = 72,
	KEY_MINUS = 73,
	KEY_PERIOD = 74,
	KEY_SLASH = 75,
	KEY_0 = 76,
	KEY_1 = 77,
	KEY_2 = 78,
	KEY_3 = 79,
	KEY_4 = 80,
	KEY_5 = 81,
	KEY_6 = 82,
	KEY_7 = 83,
	KEY_8 = 84,
	KEY_9 = 85,
	KEY_COLON = 86,
	KEY_SEMICOLON = 87,
	KEY_LESS_THAN = 88,
	KEY_EQUAL = 89,
	KEY_GREATER_THAN = 90,
	KEY_QUESTION = 91,
	KEY_AT = 92,
	KEY_CAPITAL_A = 93,
	KEY_CAPITAL_B = 94,
	KEY_CAPITAL_C = 95,
	KEY_CAPITAL_D = 96,
	KEY_CAPITAL_E = 97,
	KEY_CAPITAL_F = 98,
	KEY_CAPITAL_G = 99,
	KEY_CAPITAL_H = 100,
	KEY_CAPITAL_I = 101,
	KEY_CAPITAL_J = 102,
	KEY_CAPITAL_K = 103,
	KEY_CAPITAL_L = 104,
	KEY_CAPITAL_M = 105,
	KEY_CAPITAL_N = 106,
	KEY_CAPITAL_O = 107,
	KEY_CAPITAL_P = 108,
	KEY_CAPITAL_Q = 109,
	KEY_CAPITAL_R = 110,
	KEY_CAPITAL_S = 111,
	KEY_CAPITAL_T = 112,
	KEY_CAPITAL_U = 113,
	KEY_CAPITAL_V = 114,
	KEY_CAPITAL_W = 115,
	KEY_CAPITAL_X = 116,
	KEY_CAPITAL_Y = 117,
	KEY_CAPITAL_Z = 118,
	KEY_LEFT_BRACKET = 119,
	KEY_BACK_SLASH = 120,
	KEY_RIGHT_BRACKET = 121,
	KEY_UNDERSCORE = 122,
	KEY_GRAVE = 123,
	KEY_A = 124,
	KEY_B = 125,
	KEY_C = 126,
	KEY_D = 127,
	KEY_E = 128,
	KEY_F = 129,
	KEY_G = 130,
	KEY_H = 131,
	KEY_I = 132,
	KEY_J = 133,
	KEY_K = 134,
	KEY_L = 135,
	KEY_M = 136,
	KEY_N = 137,
	KEY_O = 138,
	KEY_P = 139,
	KEY_Q = 140,
	KEY_R = 141,
	KEY_S = 142,
	KEY_T = 143,
	KEY_U = 144,
	KEY_V = 145,
	KEY_W = 146,
	KEY_X = 147,
	KEY_Y = 148,
	KEY_Z = 149,
	KEY_LEFT_BRACE = 150,
	KEY_BAR = 151,
	KEY_RIGHT_BRACE = 152,
	KEY_TILDE = 153,
	KEY_EURO = 154,
	KEY_POUND = 155,
	KEY_YEN = 156,
	KEY_MIDDLE_DOT = 157,
	KEY_SEARCH = 158,
	KEY_DPAD_LEFT = 158,
	KEY_DPAD_RIGHT = 160,
	KEY_DPAD_UP = 161,
	KEY_DPAD_DOWN = 162,
	KEY_DPAD_CENTER = 163,
	KEY_ENTER = 164,
	KEY_PLAY = 165
}
-- camera
cc.CameraFlag =
{
    DEFAULT = 1,
    USER1 = 2,
    USER2 = 4,
    USER3 = 8,
    USER4 = 16,
    USER5 = 32,
    USER6 = 64,
    USER7 = 128,
    USER8 = 256,
}
-- light
cc.LightType = 
{
    DIRECTIONAL = 0,
    POINT = 1,
    SPOT = 2,
    AMBIENT = 3,
}
cc.LightFlag = 
{
    LIGHT0  = math.pow(2,0),
    LIGHT1  = math.pow(2,1),
    LIGHT2  = math.pow(2,2),
    LIGHT3  = math.pow(2,3),
    LIGHT4  = math.pow(2,4),
    LIGHT5  = math.pow(2,5),
    LIGHT6  = math.pow(2,6),
    LIGHT7  = math.pow(2,7),
    LIGHT8  = math.pow(2,8),
    LIGHT9  = math.pow(2,9),
    LIGHT10 = math.pow(2,10),
    LIGHT11 = math.pow(2,11),
    LIGHT12 = math.pow(2,12),
    LIGHT13 = math.pow(2,13),
    LIGHT14 = math.pow(2,14),
    LIGHT15 = math.pow(2,15),
}
-- color
cc.RED = cc.c3b(255,0,0)
cc.GREEN = cc.c3b(0,255,0)
cc.BLUE = cc.c3b(0,0,255)
cc.BLACK = cc.c3b(0,0,0)
cc.WHITE = cc.c3b(255,255,255)
cc.YELLOW = cc.c3b(255,255,0)
-- image
cc.IMAGE_FORMAT_JPEG = 0
cc.IMAGE_FORMAT_PNG = 1
cc.IMAGE_FORMAT_WEBP = 2
cc.IMAGE_FORMAT_PVR = 3
cc.IMAGE_FORMAT_ETC = 4
cc.IMAGE_FORMAT_S3TC = 5
cc.IMAGE_FORMAT_ATITC = 6
cc.IMAGE_FORMAT_TGA = 7
cc.IMAGE_FORMAT_RAW_DATA = 8
