-- 2d
require "cocos.cocos2d.Cocos2d"
require "cocos.cocos2d.Cocos2dConstants"
require "cocos.cocos2d.RendererConstants"
-- controller
require "cocos.controller.ControllerConstants"
-- ui
require "cocos.ui.GuiConstants"
-- network
require "cocos.network.NetworkConstants"
-- Spine
require "cocos.spine.SpineConstants"
-- fairygui
require "cocos.fairygui.FairyGUIConstants"
