-- 2d
require "cocos.cocos2d.Cocos2d"
require "cocos.cocos2d.Cocos2dConstants"
require "cocos.cocos2d.RendererConstants"
-- 3d
require "cocos.3d.3dConstants"
-- controller
require "cocos.controller.ControllerConstants"
-- ui
require "cocos.ui.GuiConstants"
-- network
require "cocos.network.NetworkConstants"
-- Spine
require "cocos.spine.SpineConstants"
-- physics3d
require "cocos.physics3d.physics3d-constants"
-- fairygui
require "cocos.fairygui.FairyGUIConstants"
